

spring:
   datasource:
     username: lnreddy
     password: lnreddy
     url: jdbc:mysql://localhost:3307/ecommerce

#   main:
#     log-startup-info: true

application:
  client-base-url: "*"
  cors:
    allowed-origins:
      - "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: false
    max-age: 300

jwt:
  secret: MyVeryStrongSecretKeyThatIsAtLeast32BytesLong!!
  expiration: 360000


#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.beans.factory.support: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG