spring:
  application:
    name: friendly_ecommerce
  #profile
  profiles:
    active: local

  #db migarion/version control
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  #data jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
        format_sql: true

  docker:
    compose:
      enabled: false
      file: compose.yml
      lifecycle-management: start-and-stop


  #devtools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  file:
    name: /var/log/ecommerce/application.log
  level:
    root: INFO