spring:
  application:
    name: friendly_ecommerce
  #profile
  profiles:
    active: local

  #db migarion/version control
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  #data jpa
  jpa:
    hibernate:
      ddl-auto: update



logging:
  file:
    name: /var/log/ecommerce/application.log
  level:
    root: INFO