

spring:
   datasource:
       username: ${DB_USERNAME}
       password: ${DB_PASSWORD}
       url: ${DB_URL}

#   main:
#     log-startup-info: true

application:
  client-base-url: "*"
  cors:
    allowed-origins:
      - "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: false
    max-age: 300

jwt:
  secret: ${JWT_SECRET}
  expiration: 360000


#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.beans.factory.support: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG